### ISSUE TITLE
Zoomed image position

### ISSUE THREAD

**Issue by stlr00** [dbilgin/swipe_image_gallery#1] opened 2021-08-16 16:25 UTC
Zoomed image can be in any postiion on the screen by vertical

**Comment by dbilgin** [comment] 2021-08-16 16:34
@stlr00 not exactly sure what the issue is, could you explain a bit?

**Comment by stlr00** [comment] 2021-08-16 16:45
@dbilgin Thats it. First screen is a default image view. And second is zoomed. So after that i can drag image to any postition on the screen.
![IMG_0065](https://user-images.githubusercontent.com/61075639/129599377-3901a600-0ab8-4c84-86d2-9ccc1ef2c917.PNG)
![IMG_0066](https://user-images.githubusercontent.com/61075639/129599394-0cdae20a-040f-4e80-a053-870c2030a276.PNG)

**Comment by dbilgin** [comment] 2021-08-16 16:51
@stlr00 isn't that just how zooming works? You zoom an image and then you can drag it wherever you like to view the zoomed image as you like or you can zoom back out again. Am I missing something here? What are you trying to do exactly?

**Comment by stlr00** [comment] 2021-08-16 16:54
@dbilgin I expect that the image will not move vertically until it exceeds the height of the screen. For example images in telegram works as I write.

**Comment by dbilgin** [comment] 2021-08-16 16:55
@stlr00 hmm I think I got what you mean, I'll try to check this out soon and get back to you here, thanks for opening an issue.

**Comment by dbilgin** [comment] 2022-04-11 21:56
This doesn't seem possible with `InteractiveViewer` which is what is used in this package at the moment sadly, possibly might be fixed when this issue is fixed: https://github.com/flutter/flutter/issues/58997

**Comment by dbilgin** [comment] 2024-10-05 20:43
Closing this issue, as it is not supported currently until there is an update.

**Closed as completed by dbilgin** 2024-10-05 20:43 UTC
